#!/usr/bin/env node
import { existsSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { directoryAssets } from "../server/assets.ts";
import { run } from "./run.ts";

/**
 * The npm channel and every run from source. In the npm package the UI sits
 * next to the bundle as `dist/ui`; run from source, the bundle is not there and
 * `dist/ui` is two levels up. The binary channel has its own entry with the UI
 * embedded, generated by `scripts/build.ts`.
 */
const here = fileURLToPath(new URL(".", import.meta.url));
const packaged = join(here, "ui");
const ui = directoryAssets(existsSync(packaged) ? packaged : join(here, "..", "..", "dist", "ui"));

const code = await run(process.argv.slice(2), ui, {
  out: (text) => process.stdout.write(text),
  err: (text) => process.stderr.write(text),
});
if (code !== 0) process.exit(code);
