#!/usr/bin/env bun
/**
 * Builds both delivery channels of `docs/SPEC.md` section 3, decision 2: the
 * npm bundle `dist/cli.js` for Node, and one binary per platform with the UI
 * embedded. Runs under Bun only, so `Bun.*` is allowed here.
 */
import { execFileSync } from "node:child_process";
import { mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { arch, argv, exit, platform, stderr, stdout } from "node:process";
import { contentType } from "../src/server/assets.ts";

type Target = { platform: string; arch: string; suffix?: string };

/** The six targets the specification asks for. */
const TARGETS: Target[] = [
  { platform: "darwin", arch: "x64" },
  { platform: "darwin", arch: "arm64" },
  { platform: "linux", arch: "x64" },
  { platform: "linux", arch: "arm64" },
  { platform: "windows", arch: "x64", suffix: ".exe" },
  { platform: "windows", arch: "arm64", suffix: ".exe" },
];

const GENERATED = ".build";

const USAGE = `Usage: bun run build [-- --target <name>]

  --target <name>  one binary instead of six: a platform-architecture name such
                   as darwin-arm64, or "current" for the machine building
`;

/** This machine's target, spelled the way `TARGETS` spells it. */
function currentTarget(): string {
  return `${platform === "win32" ? "windows" : platform}-${arch}`;
}

/**
 * Which binaries to compile. A release builds all six; a CI job that only runs
 * the binary it built compiles one, which is six times less work on a runner
 * that throws the other five away.
 */
function parse(args: string[]): Target[] {
  let name: string | undefined;
  for (let i = 0; i < args.length; i += 1) {
    const arg = args[i];
    if (arg === "--target") {
      i += 1;
      const value = args[i];
      if (value === undefined) throw new Error(`--target needs a name\n\n${USAGE}`);
      name = value === "current" ? currentTarget() : value;
    } else if (arg === "--help" || arg === "-h") {
      stdout.write(USAGE);
      exit(0);
    } else {
      throw new Error(`unknown argument: ${arg}\n\n${USAGE}`);
    }
  }
  if (name === undefined) return TARGETS;
  const chosen = TARGETS.filter((target) => `${target.platform}-${target.arch}` === name);
  if (chosen.length === 0) {
    const names = TARGETS.map((target) => `${target.platform}-${target.arch}`).join(", ");
    throw new Error(`--target: no target ${name}; one of ${names}, or current\n\n${USAGE}`);
  }
  return chosen;
}

let targets: Target[];
try {
  targets = parse(argv.slice(2));
} catch (error) {
  stderr.write(`build: ${error instanceof Error ? error.message : String(error)}\n`);
  exit(1);
}

function bun(args: string[]): void {
  execFileSync("bun", args, { stdio: "inherit" });
}

/** Every file of `dist/ui`, base64 encoded, as a module the binary bundles in. */
function generateEmbeddedUi(): string {
  const root = "dist/ui";
  const files: Record<string, { type: string; base64: string }> = {};
  const walk = (dir: string): void => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const path = join(dir, entry.name);
      if (entry.isDirectory()) {
        walk(path);
        continue;
      }
      const key = relative(root, path).split("\\").join("/");
      files[key] = { type: contentType(key), base64: readFileSync(path).toString("base64") };
    }
  };
  walk(root);

  const assets = join(GENERATED, "ui-assets.generated.ts");
  writeFileSync(
    assets,
    `// Generated by scripts/build.ts. Not checked in.\n` +
      `import type { EmbeddedAsset } from "../src/server/assets.ts";\n\n` +
      `export const FILES: Record<string, EmbeddedAsset> = ${JSON.stringify(files, null, 2)};\n`,
  );

  const entry = join(GENERATED, "binary.ts");
  writeFileSync(
    entry,
    `// Generated by scripts/build.ts. Not checked in.\n` +
      `import { run } from "../src/cli/run.ts";\n` +
      `import { embeddedAssets } from "../src/server/assets.ts";\n` +
      `import { FILES } from "./ui-assets.generated.ts";\n\n` +
      `const code = await run(process.argv.slice(2), embeddedAssets(FILES), {\n` +
      `  out: (text: string) => process.stdout.write(text),\n` +
      `  err: (text: string) => process.stderr.write(text),\n` +
      `});\n` +
      `if (code !== 0) process.exit(code);\n`,
  );
  return entry;
}

function size(path: string): string {
  return `${(statSync(path).size / 1024 / 1024).toFixed(1)} MiB`;
}

/**
 * `bun build --compile` leaves a 60 MiB `.<hash>-00000000.bun-build` file in the
 * working directory, under a new name every run. Ignored by git, but it piles
 * up in a checkout, so the build that made them takes them away again.
 */
function removeCompileLeftovers(): void {
  for (const name of readdirSync(".")) {
    if (name.endsWith(".bun-build")) rmSync(name, { force: true });
  }
}

rmSync("dist", { recursive: true, force: true });
rmSync(GENERATED, { recursive: true, force: true });
mkdirSync(GENERATED, { recursive: true });

bun(["run", "build:ui"]);
bun(["build", "src/cli/index.ts", "--target", "node", "--outfile", "dist/cli.js"]);
console.log(`dist/cli.js  ${size("dist/cli.js")}`);

const entry = generateEmbeddedUi();
for (const target of targets) {
  const outfile = `dist/diffalanche-${target.platform}-${target.arch}${target.suffix ?? ""}`;
  bun([
    "build",
    entry,
    "--compile",
    `--target=bun-${target.platform}-${target.arch}`,
    "--outfile",
    outfile,
  ]);
  console.log(`${outfile}  ${size(outfile)}`);
}
removeCompileLeftovers();
